### ISSUE TITLE
data in ZP of SMP-Play example does not get included in main binary

### ISSUE THREAD

**Issue by binarycounter** [Optiroc/libSFX#18]
In the `SMP-Play` example the data in the SMP zeropage doesn't seem to get included in the main binary, and never gets loaded into APURAM. 

Is this intended behavior? What would the procedure be to include the zeropage in the SMP binary?

Here's a screenshot from BizHawk's Hex Editor, showing the first few bytes of APURAM. The string `Zero!` that's included in the source file is not loaded: [Imgur Link](https://imgur.com/a/7ewNmL5)

Sorry if i'm completely misinterpreting the example. Thanks for help in advance.

**Comment by Optiroc** [comment]
At first I was a bit surprised at this question, since I didn't remember ever putting initialized data in the SPC zero page. :)

But indeed the example does just that, and I guess it's a proof of concept "if you really want to, here's how" example: In the [memory map](https://github.com/Optiroc/libSFX/blob/master/examples/SMP-Test/SMP-Play/Map.cfg#L7) for `SMP-Play` there is an extra output file statement for the usable zero page ($02-$ef, 00-01 is used by the IPL transfer routine and f0-ff is MMIO).

When building this file is indeed created. I suppose I didn't feel the need to prove the concept further, so it is never transferred to the APU, and thus the string doesn't show up in a debugger.
